# Generated by Django 6.0.4 on 2026-04-26 13:29

import apps.destinations.services
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("target_url", models.URLField(max_length=2048)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "signing_key",
                    models.CharField(
                        default=apps.destinations.services.generate_signing_key,
                        editable=False,
                        max_length=255,
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "retry_backoff_base_seconds",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="destination_status_326df1_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_retries__gte", 0), ("max_retries__lte", 20)
                        ),
                        name="destination_max_retries_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("timeout_seconds__gte", 1), ("timeout_seconds__lte", 60)
                        ),
                        name="destination_timeout_seconds_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("retry_backoff_base_seconds__gte", 1),
                            ("retry_backoff_base_seconds__lte", 300),
                        ),
                        name="destination_retry_backoff_base_seconds_range",
                    ),
                ],
            },
        ),
    ]
